version: '3'

services:
  backend:
    build: ./backend
    command: "uvicorn --host 0.0.0.0 --port 8080 app:app"
    volumes:
      - ./backend:/app/backend
    ports:
      - "8080:8080"
  frontend:
    build: ./
    stdin_open: true
    volumes:
      - ./:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start